### ISSUE TITLE
Add Docs by default

### ISSUE THREAD

**Issue by steven-esser** [nexB/skeleton#4]
Related issue: https://github.com/nexB/scancode-toolkit/issues/2345

**Comment by AyanSinhaMahapatra** [comment]
Hi, @majurg I'll take this issue?

**Comment by AyanSinhaMahapatra** [comment]
So what do we add?

1. setup a basic sphinx project 
2. Index page
3. RTD conf file
4. minimal Documentation build tests 

For 4, should we add to azure pipelines since there's the issue with travis?

**Comment by AyanSinhaMahapatra** [comment]
Should we also use the UI that you added to attributecode in [this commit](https://github.com/nexB/attributecode/commit/7f31fdb4061d838400ed55b57965c8989bfc4dc7) @johnmhoran?
That was for the docs, right?

**Comment by johnmhoran** [comment]
That could be useful @AyanSinhaMahapatra  -- but note that my `docs/source/_static/theme_overrides.css` file would need to be cleaned up, since it still contains a number of commented-out settings that I've used to experiment and fine-tune colors, margins and the like (and to remind me which settings affect which portions of the display ;-]).

If we want to include that file, I'd be happy to provide a version that's been cleaned up.  Note that I also modified `conf.py` to use `sphinx_rtd_theme` and to find the `theme_overrides.css` file.

**Comment by AyanSinhaMahapatra** [comment]
Sounds perfect. So I could add the normal doc files and then you'd just add
the cleaned up file in another PR.

**Comment by johnmhoran** [comment]
Sounds good.  I haven't visited this repo before -- where would we want the `.css` file located?  Would I just wait until you've created a folder(s) for the RTD/Sphinx files and then add it there?  And modify a `.conf.py` that you'll also add?  Not sure how this skeleton template operates.

**Comment by AyanSinhaMahapatra** [comment]
I'll ping you when the basic docs are added. So the would be under a `docs` folder which would be there in the root. The conf.py would be at `docs/source/conf.py` like the other repositories.

**Comment by AyanSinhaMahapatra** [comment]
Hey @johnmhoran now that #16 is merged, you can add template files. :bow:
